name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Paso 1: Checkout del c贸digo
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # Paso 2: Configurar Node.js 14.x (para compatibilidad con Angular)
      - name: Set up Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: '14.x'

      # Paso 3: Verificar la versi贸n de Node.js
      - name: Check Node.js version
        run: node --version

      # Paso 4: Verificar la versi贸n de npm
      - name: Check npm version
        run: npm --version

      # Paso 5: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 6: Construir y Desplegar a Azure Static Web Apps
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_GRAY_CLIFF_0C279EC1E }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/duventus"
          NODE_VERSION: '14.x' # Asegurando la versi贸n de Node.js en Azure
